// packages/react/src/components/Conversation/components/ConversationItem/index.tsx
import React, { useRef, useState } from 'react';
import { Popover, Input, Button, message, Modal } from 'antd';
import { MoreOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import type { Conversation } from '../../../../types';
import './index.less';

export interface ConversationItemProps {
  conversation: Conversation;
  active: boolean;
  onSwitchConversation: (conversation: Conversation) => void;
  onUpdateConversation: (conversation: Conversation) => void;
  onDeleteConversation: (conversationId: string) => void;
}

const ConversationItem: React.FC<ConversationItemProps> = ({
  conversation,
  active,
  onSwitchConversation,
  onUpdateConversation,
  onDeleteConversation,
}) => {
  const [isShowIcon, setIsShowIcon] = useState(false);
  const inputRef = useRef('');

  const handleMenuItemSelect = (value: string) => {
    if (value === 'deleteConversation') {
      Modal.confirm({
        title: '确定删除此会话?',
        content: '删除后无法恢复',
        okText: '确定',
        cancelText: '取消',
        onOk: () => {
          onDeleteConversation(conversation.conversationId);
          message.success(`已删除会话【${conversation?.name}】`);
        },
      });
    } else if (value === 'updateName') {
      Modal.confirm({
        title: '修改对话名',
        okText: '确定',
        cancelText: '取消',
        content: (
          <Input
            defaultValue={conversation.name}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
              (inputRef.current = e.target.value)
            }
            placeholder="请输入对话名称"
            onPressEnter={() => {
              if (inputRef.current.trim()) {
                onUpdateConversation({
                  conversationId: conversation.conversationId,
                  name: inputRef.current,
                });
                Modal.destroyAll();
              }
            }}
          />
        ),
        onOk: () => {
          if (inputRef.current.trim()) {
            onUpdateConversation({
              conversationId: conversation.conversationId,
              name: inputRef.current,
            });
            message.success('修改成功');
          }
        },
      });
    }
  };

  const menuItems = [
    {
      key: 'updateName',
      label: '更新名称',
      icon: <EditOutlined />,
    },
    {
      key: 'deleteConversation',
      label: '删除会话',
      icon: <DeleteOutlined />,
      danger: true,
    },
  ];

  return (
    <li
      className={`item ${active ? 'active' : ''}`}
      onClick={() => onSwitchConversation(conversation)}
      onMouseEnter={() => setIsShowIcon(true)}
      onMouseLeave={() => setIsShowIcon(false)}
    >
      <div className="name" title={conversation?.name}>
        {conversation?.name}
      </div>
      <Popover
        content={
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            {menuItems.map((item) => (
              <Button
                key={item.key}
                type="text"
                danger={item.danger}
                icon={item.icon}
                onClick={() => handleMenuItemSelect(item.key)}
                style={{ 'paddingLeft': '10px' }}
              >
                {item.label}
              </Button>
            ))}
          </div>
        }
        trigger="click"
        placement="bottomRight"
      >
        <MoreOutlined
          style={{
            display: isShowIcon ? 'block' : 'none',
            fontSize: 16,
            color: '#666',
            cursor: 'pointer',
          }}
        />
      </Popover>
    </li>
  );
};

export default ConversationItem;

// packages/vue-next/src/components/ConversationItem/index.vue
<template>
  <li
    :class="['item', active && 'active']"
    @click="$emit('onSwitchConversation')"
    @mouseenter="isShowIcon = true"
    @mouseleave="isShowIcon = false"
  >
    <p class="name">{{ conversation.name }}</p>
    <n-popselect
      v-model:value="selectedItem"
      :options="options"
      trigger="click"
      :on-update:value="handleMenuItemSelect"
    >
      <img v-show="isShowIcon" class="icon-conversation-more" :src="IconMore" />
    </n-popselect>
  </li>
</template>

<script setup lang="ts">
import { ref, h } from 'vue';
import type { Conversation } from '../../types';
import IconMore from '../../assets/more.svg?url';
import { NInput, NPopselect, createDiscreteApi } from 'naive-ui';

const props = defineProps<{ conversation: Conversation; active: boolean }>();
const emits = defineEmits([
  'onSwitchConversation',
  'onDeleteConversation',
  'onUpdateConversation',
]);
const { dialog, message } = createDiscreteApi(['dialog', 'message']);

const isShowIcon = ref(false); // 控制图标是否渲染
const inputValue = ref('');
const selectedItem = ref('');
const options = ref([
  {
    label: '更新名称',
    value: 'updateName',
  },
  {
    label: '删除会话',
    value: 'deleteConversation',
  },
]);

const handleMenuItemSelect = (value: string) => {
  if (value === 'deleteConversation') {
    dialog.info({
      title: '确定删除此会话?',
      positiveText: '确定',
      negativeText: '取消',
      onPositiveClick: () => {
        const { conversationId, name = '' } = props?.conversation || {};
        emits('onDeleteConversation', conversationId);
        message.success(`已删除会话【${name}】`);
      },
    });
  } else if (value === 'updateName') {
    dialog.info({
      title: '修改对话名',
      positiveText: '确定',
      negativeText: '取消',
      content: () =>
        h(NInput, {
          value: inputValue.value,
          'allow-input': (value: string) => {
            return !value.startsWith(' ') && !value.endsWith(' ');
          },
          'onUpdate:value': (v: string) => (inputValue.value = v),
          placeholder: '请输入内容',
        }),
      onPositiveClick: () => {
        emits('onUpdateConversation', {
          conversationId: props?.conversation?.conversationId,
          name: inputValue.value,
        });
        message.success('修改成功');
      },
    });
  }
};
</script>

<style lang="less" scoped>
@import url('./index.less');
</style>
