// packages/vue-next/src/components/Welcome/index.vue
<template>
  <div class="welcome">
    <section class="welcome-title">{{ content.title }}</section>
    <section class="welcome-describe">{{ content.describe }}</section>
    <section class="welcome-prompt">
      <div class="welcome-prompt-title">{{ content.prompt.title }}</div>
      <div class="welcome-prompt-list">
        <div v-for="(item, i) in content.prompt.list" :key="i" class="welcome-prompt-item" @click="setInput(item)">
          {{ item }}
        </div>
      </div>
    </section>
  </div>
</template>
<script setup lang="ts">
import { computed } from 'vue';

interface IWelcomeContent {
  title: string;
  describe: string;
  prompt: {
    title: string;
    list: string[];
  };
}

interface Props {
  content: IWelcomeContent
}

const props = withDefaults(defineProps<Props>(), {
  content: () => {
    return {
      title: '',
      describe: '',
      prompt: {
        title: '',
        list: [],
      },
    }
  }
});

const emit = defineEmits<{'setInput': [item: string]}>();

/**
 * Welcome props content
 * @type {IWelcomeContent}
 */
const content = computed(() => {
  return props.content;
});

/**
 * 点击 prompt 列表触发事件
 * @param {string} item prompt item
 */
const setInput = (item: string) => {
  emit('setInput', item)
};

</script>
<style scoped lang="less">
@import url('./index.less');
</style>

// packages/react/src/components/Welcome/index.tsx
import React from 'react';
import { Typography, List } from 'antd';
import type { IWelcomeProps } from '../../types/index';
import './index.less';

const { Title, Paragraph, Text } = Typography;

const Welcome: React.FC<IWelcomeProps> = ({ content, onSetInput }) => {
  const {
    title = '',
    describe = '',
    prompt = { title: '', list: [] },
  } = content;

  const handleItemClick = (item: string) => {
    onSetInput(item);
  };

  return (
    <div className="welcome">
      <section className="welcome-title">
        <Title level={4} style={{ margin: 0, color: 'inherit' }}>
          {title}
        </Title>
      </section>

      <section className="welcome-describe">
        <Paragraph style={{ margin: 0, color: 'inherit' }}>
          {describe}
        </Paragraph>
      </section>

      <section className="welcome-prompt">
        <div className="welcome-prompt-title">
          <Text type="secondary">{prompt.title}</Text>
        </div>
        <div className="welcome-prompt-list">
          <List
            split={false}
            dataSource={prompt.list}
            renderItem={(item) => (
              <List.Item style={{ padding: 0, marginBottom: 12 }}>
                <div
                  className="welcome-prompt-item"
                  onClick={() => handleItemClick(item)}
                >
                  {item}
                </div>
              </List.Item>
            )}
          />
        </div>
      </section>
    </div>
  );
};

export default Welcome;
