// packages/vue-next/src/container/Welcome/index.vue
<template>
  <Welcome :content="config?.welcome?.options?.content" @setInput="setItemToInput" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Welcome from '../../components/Welcome/index.vue';
import { chatStoreInject } from '../../hooks/useChatStore';
import { pushMessageInject } from '../../hooks/usePushMessage';

const chatStoreHook = chatStoreInject();

const { setInput } = pushMessageInject();

const config = computed(() => {
  return chatStoreHook.state.chatConfig;
});

const setItemToInput = async (item: string) => {
  setInput(item);
};
</script>

<style scoped></style>

// packages/react/src/container/Welcome/index.tsx
import React, { useContext } from 'react';
import Welcome from '../../components/Welcome';
import { ChatStoreContext } from '../../contexts';

interface WelcomeContainerProps {
  onSendMsg?: (query: string) => void;
}

const WelcomeContainer: React.FC<WelcomeContainerProps> = ({ onSendMsg }) => {
  const chatStore = useContext(ChatStoreContext);

  if (!chatStore) {
    return null;
  }

  const config = chatStore?.state?.chatConfig || {};
  const content = config?.welcome?.options?.content || {
    title: '',
    describe: '',
    prompt: {
      title: '',
      list: [],
    },
  };

  const handleSetInput = async (item: string) => {
    onSendMsg?.(item);
  };

  return <Welcome content={content} onSetInput={handleSetInput} />;
};

export default WelcomeContainer;
