// packages/vue-next/src/components/ChatMessages/index.vue
<template>
  <list>
    <template v-for="(_, slot) in $slots" #[slot]="props">
      <slot :name="slot" v-bind="props"/>
    </template>
  </list>
  <empty />
</template>

<script setup lang="ts">
  import List from './components/List.vue'
  import Empty from './components/Empty.vue'
  import useChatList, { provideStore } from './hooks/index.js';

  const props = defineProps({
    data: Array,
    config: Object
  });

const store = useChatList(props);
provideStore(store);

console.log(store,'storestore')
</script>

<style lang="less" scoped>
  .chat-message-list {
    position: relative;
    height: 100%;
  }
</style>

// packages/react/src/components/ChatMessages/index.tsx
import React from 'react';
import List from './components/List/index';
import Empty from './components/Empty/index';
import { ChatListContext } from './contexts';
import { useChatList } from './hooks/useChatList';
import type { IChatMessagesProps } from '../../types/index';
import './index.less';

const ChatMessages: React.FC<IChatMessagesProps> = ({
  data,
  config,
  ...scopeSlots
}) => {
  const store = useChatList({ data, config });

  return (
    <ChatListContext.Provider value={store}>
      <div className="chat-message-list">
        <List {...scopeSlots} />
        <Empty />
      </div>
    </ChatListContext.Provider>
  );
};

export default ChatMessages;
