// packages/react/src/components/Conversation/index.tsx
import React from 'react';
import { Button } from 'antd';
import ConversationItem from './components/ConversationItem';
import {
  IConversationProps,
  Conversation as IConversation,
} from '../../types/index';
import './index.less';

const Conversation: React.FC<IConversationProps> = ({
  conversationId,
  conversationList,
  onAddConversation,
  onSwitchConversation,
  onUpdateConversation,
  onDeleteConversation,
}) => {
  const handleAddConversation = async () => {
    onAddConversation?.();
  };

  const handleSwitchConversation = (conversation: IConversation) => {
    onSwitchConversation?.(conversation);
  };

  const handleUpdateConversation = (conversation: IConversation) => {
    onUpdateConversation?.(conversation);
  };

  const handleDeleteConversation = (conversationId: string) => {
    onDeleteConversation?.(conversationId);
  };

  return (
    <div className="layout">
      <aside className="sidebar">
        <Button
          className="icon-new"
          type="primary"
          onClick={handleAddConversation}
        >
          + 新建
        </Button>
        <ul>
          {conversationList?.map((conversation: IConversation) => (
            <ConversationItem
              key={conversation.conversationId}
              conversation={conversation}
              active={conversation.conversationId === conversationId}
              onSwitchConversation={handleSwitchConversation}
              onDeleteConversation={handleDeleteConversation}
              onUpdateConversation={handleUpdateConversation}
            />
          ))}
        </ul>
      </aside>
    </div>
  );
};

export default Conversation;

// packages/vue-next/src/container/Conversation/index.vue
<template>
  <div class="layout">
    <aside class="sidebar">
      <n-button class="icon-new" @click="handleCompAddConversation">
        + 新建
      </n-button>
      <ul>
        <conversation-item
          v-for="conversation in conversationList"
          :key="conversation.conversationId"
          :conversation="conversation"
          :active="conversation.conversationId === curConversationId"
          @onSwitchConversation="handleCompSwitchConversation(conversation)"
          @onDeleteConversation="handleCompDeleteConversation"
          @onUpdateConversation="handleCompUpdateConversation"
        ></conversation-item>
      </ul>
    </aside>
  </div>
</template>

<script setup lang="ts">
import ConversationItem from '../../components/ConversationItem/index.vue';
import { NButton } from 'naive-ui';
import { conversationInject } from '../../hooks/useConversation';

defineOptions({
  name: 'ms-chat-conversation',
});

const emits = defineEmits([
  'onAddConversation',
  'onSwitchConversation',
  'onDeleteConversation',
  'onUpdateConversation',
]);

const conversationHook: any = conversationInject();
const {
  conversationList,
  curConversationId,
} = conversationHook || {};
const handleCompAddConversation = () => {
  emits('onAddConversation');
};

const handleCompSwitchConversation = (conversation: any) => {
  emits('onSwitchConversation', conversation);
};

const handleCompUpdateConversation = (params: any) => {
  emits('onUpdateConversation', params);
};

const handleCompDeleteConversation = (conversationId: any) => {
  emits('onDeleteConversation', conversationId);
};
</script>

<style scoped lang="less">
@import url('./index.less');
</style>
