// packages/react/src/container/ChatMessages/index.tsx
import React, { useContext } from 'react';
import ChatMessagesComponent from '../../components/ChatMessages/index';
import { ChatStoreContext } from '../../contexts';

interface ChatMessagesContainerProps {
  [scopeSlot: string]: any;
}

const ChatMessagesContainer: React.FC<ChatMessagesContainerProps> = (
  scopeSlots
) => {
  const store = useContext(ChatStoreContext);
  const messageList = store?.state?.messageList || [];
  const config = {
    bubble: store?.state?.chatConfig?.bubble
  };
  return <ChatMessagesComponent data={messageList} config={config} {...scopeSlots} />;
};

export default ChatMessagesContainer;

// packages/vue-next/src/container/ChatMessages/index.vue
<template>
  <ChatMessages :data="messageList" :config="config">
    <template v-for="(_, slot) in $slots" #[slot]="props">
      <slot :name="slot" v-bind="props"/>
    </template>
  </ChatMessages>
</template>

<script setup lang="ts">
import { ref, computed, h } from 'vue';
import { chatStoreInject } from '../../hooks/useChatStore';
import ChatMessages from '../..//components/ChatMessages/index.vue';

const chatStore = chatStoreInject();
const messageList = computed(() => {
  return chatStore.state.messageList;
});
const config = computed(() => {
  return {
    bubble: chatStore.state.chatConfig?.bubble
  };
});
</script>

<style scoped></style>
