// packages/react/src/container/Header/index.tsx
import React, { useContext } from 'react';
import HeaderComponent from '../../components/Header';
import { ChatStoreContext } from '../../contexts';

const HeaderContainer: React.FC = () => {
  const chatStore = useContext(ChatStoreContext);

  if (!chatStore) {
    return null;
  }

  const headerHidden = chatStore?.state?.chatConfig?.header?.hidden;
  // 当前会话标题
  const curTitle = chatStore?.state?.chatConfig?.header?.options?.title;

  if (headerHidden) {
    return null;
  }

  return <HeaderComponent title={curTitle} />;
};

export default HeaderContainer;

// packages/vue-next/src/container/Header/index.vue
<template>
  <Header v-if="!headerHidden" :title="curConversationName"/>
</template>

<script setup lang="ts">
  import { computed } from 'vue';
  import Header from '../../components/Header/index.vue';
  import { chatStoreInject } from '../../hooks/useChatStore';
  const chatStore = chatStoreInject();
  // 当前会话标题
  const curConversationName = computed(() => {
    return chatStore?.state?.chatConfig?.header?.options?.title;
  });
  const headerHidden = computed(() => {
    return chatStore?.state?.chatConfig?.header?.hidden;
  });
</script>

<style scoped></style>
