// packages/react/src/components/ChatMessages/components/Empty/index.tsx
import React, { useContext } from 'react';
import { Empty } from 'antd';
import { ChatListContext } from '../../contexts';

const EmptyComponent: React.FC = () => {
  const store = useContext(ChatListContext);

  if (!store?.isEmptyData) return null;

  return <Empty description="暂无数据" />;
};

export default EmptyComponent;

// packages/vue-next/src/components/ChatMessages/components/Empty.vue
<template>
  <n-empty description="暂无数据" v-if="isEmptyData"> </n-empty>
</template>

<script setup lang="ts">
import { NEmpty } from 'naive-ui';
import { injectStore } from '../hooks/index.js';

const store = injectStore();
const { isEmptyData } = store;
</script>

<style lang="less" scoped></style>
