// packages/react/src/components/ChatMessages/components/List/index.tsx
import React, { useContext } from 'react';
import { List as AntdList } from 'antd';
import VirtualList from 'rc-virtual-list';
import ChatMessageBubble from '../../../ChatMessageBubble/index';
import { ChatListContext } from '../../contexts';
import FloatBtn from '../FloatBtn/index';
import './index.less';

interface IListProps {
  [scopeSlot: string]: any;
}

const List: React.FC<IListProps> = (scopeSlots = {}) => {
  const store = useContext(ChatListContext);

  if (store?.isEmptyData) return null;

  return (
    <>
      <div className="chat-message-list" ref={store?.scrollbarRef}>
        <AntdList split={false}>
          <VirtualList
            ref={store?.virtualListRef} // 绑定 virtualListRef
            style={{ width: '100%' }}
            itemKey="id"
            height={store?.containerHeight}
            data={store?.runData || []}
            onScroll={store?.handleScroll}
          >
            {(item: any) => (
              <AntdList.Item key={item.id}>
                <ChatMessageBubble {...item} {...scopeSlots} />
              </AntdList.Item>
            )}
          </VirtualList>
        </AntdList>
      </div>
      <FloatBtn />
    </>
  );
};

export default List;

// packages/vue-next/src/components/ChatMessages/components/List.vue
<template>
  <div v-if="!isEmptyData" class="chat-message-list">
    <!-- <n-scrollbar
      v-if="!useVirtual"
      style="max-height: 100%"
      ref="scrollbarRef"
      @scroll="handleScroll"
    >
      <div v-for="item in data" :key="item.id">
        <ChatBubble v-bind="item" >
          <template v-for="(_, slot) in $slots" #[slot]="props">
            <slot :name="slot" v-bind="props"/>
          </template>
        </ChatBubble>
      </div>
    </n-scrollbar> -->
    <n-virtual-list
      style="max-height: 100%"
      :item-size="58"
      :items="runData"
      :key-field="'id'"
      item-resizable
      ref="scrollbarRef"
      @scroll="handleScroll"
    >
      <template #default="{ item }">
        <ChatBubble v-bind="item">
          <template v-for="(_, slot) in $slots" #[slot]="props">
            <slot :name="slot" v-bind="props"/>
          </template>
        </ChatBubble>
      </template>
    </n-virtual-list>

    <float-btn />
  </div>
</template>

<script setup lang="ts">
import { NScrollbar, NVirtualList } from 'naive-ui';
import ChatBubble from '../../ChatBubble/index.vue';
import FloatBtn from './FloatBtn.vue';
import { injectStore } from '../hooks/index.js';

const store = injectStore();

const { data, runData, scrollbarRef, handleScroll, isEmptyData } = store;

</script>

<style lang="less" scoped>
.chat-message-list {
  position: relative;
  height: 100%;
}
</style>
